name: Deploy Portfolio
on:
  push:
    branches: [ main ] # This triggers the robot every time you push code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDOR }}
          service_accoutn: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Step A & B — Build and Push to Artifact Registry
      - name: Build and Push Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/portfolio-repo/portfolio-site:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/portfolio-repo/portfolio-site:latest

      # Step C — Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy portfolio-website \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/portfolio-repo/portfolio-site:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated